---
title: "Quantitative Section of the 2026 HUSOE ELPS Methods and Data Institute"
author: "Nathan Alexander, PhD"
institute: 
  - "Howard University School of Education"
  - "Center for Applied Data Science and Analytics"
---

Thank you for joining us. This site is to support your learning during this Quantitative Section of the *2026 Howard University ELPS Methods and Data Institute*. My name is [Professor Nathan Alexander](about.qmd){target="_blank"} and I will be today's facilitator.

Today's workshop is about quantitative data collection and analysis. 

For this workshop, I will take a Computational Studies in Education (CSIE) approach. CSIE is an interdisciplinary field that uses computational methods — like data analysis, modeling, and machine learning — to study how people learn, behave, and interact in social and educational contexts. At its core, it blends ideas from education, the social sciences, and computer science.

Instead of relying only on traditional paper-based methods that focus on small-scale surveys or interviews, computational studies uses data to drawn various conclusions that extend beyond what is taught in most introductory and intermediate courses in statistics. In particular, this field works with large-scale and complex data when engage in quantitative analysis.

Given our education focus, we'll focus on survey methods and I'll introduce some interesting tools and methods for computational text analysis -- which, with time and care, can be applied to your interviews and focus groups.

For today's institute, we will use an alternative to SPSS known as *R*. The software platform is free and online, meaning you will not need to download anything to your computer. However, if you'd like to get the software set up locally, instructions are [here](computing.qmd){target="_blank"}.

## Learning Outcomes

By the end of this workshop, you will be able to:

- Describe basic data analysis workflows using real-world educational data 
- Produce a technical reports using what is called an R Markdown (in Quarto)  
- Import, clean, and visualize data using `tidyverse` tools  
- Formulate and interpret equity-focused research questions using data  
- Extend these methods to support your dissertation research and analysis

## Schedule

| Part | Topic                          | Duration   | Time            |
|------|--------------------------------|------------|-----------------|
|      | Introductions & site orientation     | 10 minutes | 10:00–10:10 AM    |
|      | Tech setup                     | 15 minutes | 10:10–10:25 AM    |
|      | Tech break (optional support)                   | 5 minutes | 10:25–10:30 AM    |
| 1    | [Getting started in R and Posit](parts/part01.qmd) | 30 minutes | 5:10–5:40 PM    |
|      | Break                          | 5 minutes  | 5:40–5:45 PM    |
| 2    | [Conducting a literature scan](parts/part02.qmd) | 15 minutes | 5:45–6:00 PM    |
|      | Break                          | 5 minutes  | 6:00–6:05 PM    |
| 3    | [Working with large-scale data](parts/part03.qmd)  | 45 minutes | 6:05–6:50 PM    |
|      | Q&A                            | 10 minutes | 6:50–7:00 PM    |

## Recommended readings

Baumer, B. S., Kaplan, D. T., & Horton, N. J. (2017). *Modern data science with R*. Chapman and Hall/CRC.

Grolemund, G., & Wickham, H. (2017). *R for data science: Import, tidy, transform, visualize, and model data*. O’Reilly Media. [https://r4ds.had.co.nz/](https://r4ds.had.co.nz/){target="_blank"}

Knaflic, C. N. (2015). *Storytelling with data: A data visualization guide for business professionals*. Wiley.

Peng, R. D. (2016). *R programming for data science*. Leanpub. [https://bookdown.org/rdpeng/rprogdatascience/](https://bookdown.org/rdpeng/rprogdatascience/){target="_blank"}

RStudio Education (n.d.). Learning R for Beginners. Online. [https://education.rstudio.com/learn/beginner/](https://education.rstudio.com/learn/beginner/){target="_blank"}

Wickham, H. (2019). *Advanced R* (2nd ed.). Chapman and Hall/CRC. [https://adv-r.hadley.nz/](https://adv-r.hadley.nz/){target="_blank"}


